// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    id, title, description, user_id, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) RETURNING id, created_at, updated_at, title, description, thumbnail_url, video_url, user_id
`

type CreateVideoParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UserID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.VideoUrl,
		&i.UserID,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos
WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, id)
	return err
}

const getVideo = `-- name: GetVideo :one
SELECT id, created_at, updated_at, title, description, thumbnail_url, video_url, user_id
FROM videos
WHERE id = ?
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.VideoUrl,
		&i.UserID,
	)
	return i, err
}

const getVideos = `-- name: GetVideos :many
SELECT id, created_at, updated_at, title, description, thumbnail_url, video_url, user_id
FROM videos
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetVideos(ctx context.Context, userID uuid.UUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.ThumbnailUrl,
			&i.VideoUrl,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :exec
UPDATE videos
SET title = ?,
    description = ?,
    thumbnail_url = ?,
    video_url = ?,
    user_id = ?
WHERE id = ?
`

type UpdateVideoParams struct {
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	ThumbnailUrl *string   `json:"thumbnail_url"`
	VideoUrl     *string   `json:"video_url"`
	UserID       uuid.UUID `json:"user_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.db.ExecContext(ctx, updateVideo,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.VideoUrl,
		arg.UserID,
		arg.ID,
	)
	return err
}
